### ISSUE TITLE
Remove distill module

### ISSUE THREAD

**Issue by achyudh** [karkaroff/hedwig#32]
If as discussed, distillation won't be a part of hedwig, the models/distill directory along with the placeholder driver method in it has to be removed: https://github.com/karkaroff/hedwig/blame/bellatrix/models/distill

**Comment by Ashutosh-Adhikari** [comment]
Can you please remove it. As I removing it might cause a conflict. Thanks.

**Comment by achyudh** [comment]
Oh sure thing!

**Comment by achyudh** [comment]
This issue was fixed in 0cdb70ac3322a7187ae5443b641fd44709aef60a
