### ISSUE TITLE
Fix README files

### ISSUE THREAD

**Issue by achyudh** [karkaroff/hedwig#7]
We need to fix README files for all models, along with the project README. Model README files contain datasets that have been removed from the project, and the project README still reads Castor.

**Comment by daemon** [comment]
Just a gentle reminder that this line in the main README should be changed to our paper, of course after  the arXiv push:
> Reg-LSTM: Regularized LSTM for document classification ~(Merity et al.)~ (Adhikari et al., NAACL 2019)

**Comment by achyudh** [comment]
Yes, I remember this. But we can only do that after we have something to link it to like arXiv or the camera-ready

**Comment by achyudh** [comment]
Closing this as there is an identical issue in castorini/hedwig: https://github.com/castorini/hedwig/issues/3
